<a href="https://colab.research.google.com/github/hyesungKomet/rokaf_ai/blob/main/Elice_2_3_Recurrent_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# RNN(Recurrent Neural Network

## Sequential Data
* Sequential data(순차 데이터)를 처리하기 위한 모델 ex) 시계열 데이터
  - 데이터 내 객체 간 순서가 중요!
  - 날씨, 강수량, 주식 등 -> 예측 : 강수량 예측(Precipitation Forecasting) by Google(MetNet)
  - 자연어 데이터 -> 음성인식, 번역기, 챗봇
  - 오디오 파일 -> 음악 장르 분석

## FC Layer
RNN에서 FC Layer(Fully-Connected Layer)가 적합하지 않은 이유
* FC Layer은 입력 노드와 출력 노드의 개수가 정해짐 
but 순차데이터는 그걸 이루는 객체 수가 바뀔 수 있음
  * ex) I am hungry 에서 I am so hungry로 바꾸면 FC Layer에서는 입력이 3개로 정해졌으니 so에서 끊어버려 의미를 완전히 상실해버린다

* FC Layer은 순서 고려가 불가능 but 순차데이터는 순서가 중요!

## Embedding  
: 각 단어들을 숫자로 된 벡터로 변환
* 단순한 Encoding

![image](https://postfiles.pstatic.net/MjAxODA4MDlfMjI5/MDAxNTMzODIzMTQwNDky.igqtWuHq1_XFexz9jHtUoYhuKBkfdaXzrTMbXXmizmog.k2eHyady3gYgZKwWF2ofZ4IKRZ8YNwQzpdHZhwVjo-cg.PNG.timtaeil/image.png?type=w773)
* One-hot Encoding

![image.jpg](https://postfiles.pstatic.net/MjAxODA4MDlfMTU2/MDAxNTMzODIzNTc0NTc5.RNpGTrnWJuXen35rQ0YlignF0wdkVjMkrOxsS4gh8IAg.Nb4Ay_AMNnhSlHz0rOiuZhVB6nSv7qqcu8F7t8Ah_BQg.PNG.timtaeil/image.png?type=w773)

원핫 인코딩의 문제점  
* 공간낭비  
  단어가 많아질수록 0으로 채워지는 공간만 많아짐(희소벡터)
* 단어의 유사도
  원한 인코딩으로는 단어의 유사도를 표현하지 못함
  단어 간 유사도는 벡터 간의 거리로 나타난다  
  ex) 남자, 여자와 왕, 여왕 간의 벡터의 거리가 비슷함  
  but 원핫 인코딩을 하면 모든 벡터간 거리가 같아서 이를 못나타낸다  

* Word2Vec: 주어진 단어를 벡터로 변환하는 모델
  - CBOW Model
  - Skip-Gram Model


  ### CBOW Model
  : 주변 단어로부터 중심 단어를 추측하는 신경망  
  ![](https://lilianweng.github.io/posts/2017-10-15-word-embedding/word2vec-cbow.png)
  여기 자세히 나와있다...  
  https://lilianweng.github.io/posts/2017-10-15-word-embedding/

  ![](https://1.bp.blogspot.com/-gjnDTyhZOmQ/XPDtkX8qtFI/AAAAAAAABtU/lxYFusQZd4UwT9E3aM_mgVj8ldFbYdcawCLcBGAs/s400/image001.png)

  윈도우 크기: 주변 단어 몇 개를 볼 지
  ex) 윈도우가 1: 주변 단어 2개, 윈도우가 2: 주변 단어 4개

* 단어 별 ID를 순서대로 부여하고 다 ID로 임베딩해준 다음 원핫으로 표현하여 모델에 넣는다!

* [i like natural language processing] -> Word ID: [0 1 2 3 4]  
![](https://1.bp.blogspot.com/-sgsYUYw1AKw/XP9WuOoJD2I/AAAAAAAABuE/KJemBqYMHhErtN7noNMVLIy6nQc5K5FHgCLcBGAs/s1600/Capture.PNG)

* ![](https://1.bp.blogspot.com/-NxS7TEIHumY/XP9XBdZzQEI/AAAAAAAABuM/3dAf7K39zMw0g5rCfvaYZvCwwyEfCAH8gCLcBGAs/s1600/Capture.PNG)


  ### Skip-Gram Model
  : 중심 단어로부터 주변 단어 추측하는 신경망
  * 학습 시간은 CBOW가 빠르지만 말뭉치가 커질수록 Skip-Gram이 더 뛰어난 성능을 보인다

  CBOW의 반대를 생각하면 될듯... 수치적인거나 모델 구조는 따로 더 공부해야될 듯 하다...

단어의 문맥적 의미를 수치적으로 보전하기에 One-hot 인코딩의 단점 극복하여 단어 간 유사성을 나타낼 수 있다!!

## Hidden State
: Internal state that is updated as a sequence is processed

순환구조 구현의 핵심 요소!!

## Vanila RNN
![](https://jsideas.net/assets/materials/20190216/vanilla_rnn.png)

세 개의 FC Layers
* $$W_{hh}: hiden state(h_{t-1})을 변환$$
* $$W_{xh}: 입력값(x_t)을 변환$$
* $$W_{yh}: 출력값(y_t)을 변환$$
* $$y_t = W_{hy} h_t$$

### Hidden State
* 입력값에 대한 새로운 hidden state에 대한 계산이 이루어짐
* 이전 시점에 생성된 hidden state를 다음 시점에 이용!
* 입력값들의 상관관계 & 경향성 정보 압축 저장
* 모델의 내부적인 값 -> "Memory"

* Parameter Sharing
  * Hidden State와 출력값 계산을 위한 모든 FC Layer를 모든 시점의 입력값이 재사용
  * 세 FC Layer가 파라미터의 전부!!

![](https://blog.acolyer.org/wp-content/uploads/2019/02/rnnvis-fig-2.jpeg?w=480)

## Loss
* BPTT(Back Propagation Through Time) - 역전파가 시간 흐름에 따라 작동
* 각 시점의 출력값과 실제 값 비교하여 Loss 구함


## Vanila RNN의 문제점
* Gradient Vanishing(기울기 소실)
  입력값의 길이가 매우 길어질 경우 - 초기 입력값과 끝의 출력값 사이의 기울기가 매우 작아짐
  -> Long Term Dependancy(장기 의존성) 다루기 힘들어짐

* HOW? --> LSTM man~

## Vanila RNN 종류
* many-to-one(다대일 구조)  
  한 시점의 출력값만 사용
* many-to-many(다대다 구조)  
  여러 시점의 입출력값 사용
* Encoder-Decoder  
  입력값들을 받아 특정 hidden state로 인코딩 후 이를 통해 새로운 출력값 만드는 구조
  ![](https://miro.medium.com/max/1400/1*1JcHGUU7rFgtXC_mydUA_Q.jpeg)



# One-hot Encoding 구현

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

In [ ]:
def set_token(texts):
  tokenizer = Tokenizer()
  tokenizer.fit_on_texts(texts)
  return tokenizer

In [ ]:
def text2seq(text, tokenizer):
  return tokenizer.texts_to_sequences([text])[0]

def seq2onehot(seq,num_word):
  return to_categorical(seq,num_classes=num_word+1)

In [ ]:
text1 = "stand on the shoulders of giants"
text2 = "I can stand on mountains"

In [ ]:
tokenizer = set_token([text1, text2])

In [ ]:
print("단어 수: ", len(tokenizer.word_index))
print("단어 인덱스: ", tokenizer.word_index)

단어 수:  9
단어 인덱스:  {'stand': 1, 'on': 2, 'the': 3, 'shoulders': 4, 'of': 5, 'giants': 6, 'i': 7, 'can': 8, 'mountains': 9}


In [ ]:
seq = text2seq(text2, tokenizer)
print(seq)

[7, 8, 1, 2, 9]


In [ ]:
onehot1 = seq2onehot(seq, len(tokenizer.word_index))
print(onehot1)
print("한 단어를 표현하는 길이: ", len(onehot1[0]))

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
한 단어를 표현하는 길이:  10


# Vanila RNN Model 구현

In [11]:
import tensorflow as tf
from tensorflow.keras import layers, Sequential

# 첫번째 모델
def build_model1():
    model = Sequential()
    
    model.add(layers.Embedding(10, 5)) #input dim(전체 단어 개수), output dim(벡터 길이)
    model.add(layers.SimpleRNN(3)) # hidden state 크기
    
    return model

# 두번째 모델
def build_model2():
    model = Sequential()
    
    model.add(layers.Embedding(256,100))
    model.add(layers.SimpleRNN(20))
    model.add(layers.Dense(10, activation="softmax"))
    
    return model
    
def main():
    model1 = build_model1()
    print("=" * 20, "첫번째 모델", "=" * 20)
    model1.summary()
    
    print()
    
    model2 = build_model2()
    print("=" * 20, "두번째 모델", "=" * 20)
    model2.summary()

if __name__ == "__main__":
    main()

==================== 첫번째 모델 ====================
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 5)           50        
                                                                 
 simple_rnn (SimpleRNN)      (None, 3)                 27        
                                                                 
Total params: 77
Trainable params: 77
Non-trainable params: 0
_________________________________________________________________

==================== 두번째 모델 ====================
Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, None, 100)         25600     
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 20)                2420      
     

# Vanila RNN으로 IMDb data 학습
![](https://static.amazon.jobs/teams/53/thumbnails/IMDb_Jobs_Header_Mobile.jpg?1501027253)

IMDb(Internet Movie Database): 영화 정보를 데이터베이스화해서 제공함

* 데이터셋: 사용자의 영화 리뷰를 긍정/부정으로 분류(2클래스)

* -> Sentimental Analysis(감성 분석)에 많이 쓰임!


In [12]:
import tensorflow as tf
from tensorflow.keras import layers, Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences

def load_data(num_words, max_len):
    # imdb 데이터셋. 데이터셋에서 단어는 num_words 개를 가져옴
    (X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=num_words)

    # 단어 개수가 다른 문장들을 Padding을 추가하여
    # 단어가 가장 많은 문장의 단어 개수로 통일.
    X_train = pad_sequences(X_train, maxlen=max_len) # 단어 개수 통일
    X_test = pad_sequences(X_test, maxlen=max_len)
    
    return X_train, X_test, y_train, y_test

def build_rnn_model(num_words, embedding_len):
    model = Sequential()
    
    # 모델
    model.add(layers.Embedding(num_words, embedding_len))
    model.add(layers.SimpleRNN(16))
    model.add(layers.Dense(1,activation="sigmoid")) #긍정일 확률 하나만 뽑는다
    
    return model

def main(model=None, epochs=5):
    # IMDb 데이터셋에서 가져올 단어의 개수
    num_words = 6000
    
    # 각 문장이 가질 수 있는 최대 단어 개수
    max_len = 130
    
    # 임베딩 된 벡터의 길이
    embedding_len = 100
    
    # IMDb 데이터셋 불러오기
    X_train, X_test, y_train, y_test = load_data(num_words, max_len)
    
    if model is None:
        model = build_rnn_model(num_words, embedding_len)
    
    # optimizer와 loss 함수
    optimizer = Adam(learning_rate=0.001)
    model.compile(optimizer=optimizer, loss="binary_crossentropy", metrics=["accuracy"]) #값 하나가 확률로 해석되는 경우 BCE를 써야 함!
    
    # 모델 학습을 위한 hyperparameter
    hist = model.fit(X_train, y_train, epochs=epochs, batch_size=100, validation_split=0.2, shuffle=True,verbose=2)
    
    # 모델을 테스트 데이터셋으로 테스트
    test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
    print()
    print("테스트 Loss: {:.5f}, 테스트 정확도: {:.3f}%".format(test_loss, test_acc * 100))
    
    return optimizer, hist

if __name__=="__main__":
    main()


17473536/17464789 [==============================] - 0s 0us/step
Epoch 1/5
200/200 - 11s - loss: 0.5675 - accuracy: 0.6916 - val_loss: 0.4436 - val_accuracy: 0.8070 - 11s/epoch - 54ms/step
Epoch 2/5
200/200 - 10s - loss: 0.3683 - accuracy: 0.8429 - val_loss: 0.4404 - val_accuracy: 0.7996 - 10s/epoch - 51ms/step
Epoch 3/5
200/200 - 9s - loss: 0.2495 - accuracy: 0.9049 - val_loss: 0.4047 - val_accuracy: 0.8308 - 9s/epoch - 46ms/step
Epoch 4/5
200/200 - 9s - loss: 0.1550 - accuracy: 0.9484 - val_loss: 0.4397 - val_accuracy: 0.8332 - 9s/epoch - 45ms/step
Epoch 5/5
200/200 - 9s - loss: 0.0832 - accuracy: 0.9772 - val_loss: 0.5026 - val_accuracy: 0.8216 - 9s/epoch - 45ms/step

테스트 Loss: 0.50740, 테스트 정확도: 81.912%


# 심층 Vanila RNN

In [13]:
import tensorflow as tf
from tensorflow.keras import layers, Sequential
from tensorflow.keras.optimizers import Adam
import numpy as np

def load_data(num_data, window_size):
    freq1, freq2, offsets1, offsets2 = np.random.rand(4, num_data, 1)
     # sin 함수로 만든 간단한 시계열 데이터
    time = np.linspace(0, 1, window_size + 1)
    series = 0.5 * np.sin((time - offsets1) * (freq1 * 10 + 10))
    series += 0.1 * np.sin((time - offsets2) * (freq2 * 10 + 10))
    series += 0.1 * (np.random.rand(num_data, window_size + 1) - 0.5)
    
    num_train = int(num_data * 0.8)
    X_train, y_train = series[:num_train, :window_size], series[:num_train, -1]
    X_test, y_test = series[num_train:, :window_size], series[num_train:, -1]
    
    X_train = X_train[:, :, np.newaxis]
    X_test = X_test[:, :, np.newaxis]
    
    return X_train, X_test, y_train, y_test

def build_rnn_model(window_size):
    model = Sequential()

    # SimpleRNN 기반 모델
    model.add(layers.SimpleRNN(20, input_shape=(window_size,1)))
    model.add(layers.Dense(1))

    return model

def build_deep_rnn_model(window_size):
    model = Sequential()

    # 여러개의 SimpleRNN을 가지는 모델
    model.add(layers.SimpleRNN(20, return_sequences=True, input_shape=(window_size,1))) 
    #return_sequences: simplernn은 default: 다대일(마지막 출력만)
    # 여기서는 여러 층에서의 출력값을 다 입력값으로 쓰도록 설정함
    model.add(layers.SimpleRNN(20))
    model.add(layers.Dense(1))

    return model

def run_model(model, X_train, X_test, y_train, y_test, epochs=20, name=None):
    # optimizer와 loss 함수
    optimizer = Adam(learning_rate=0.001)
    model.compile(optimizer=optimizer, loss='mse')

    #  hyperparameter
    hist = model.fit(X_train, y_train, epochs=epochs, batch_size=256,shuffle=True,verbose=2)
    
    # 테스트 데이터셋으로 모델을 테스트
    test_loss = model.evaluate(X_test, y_test, verbose=0)
    print("[{}] 테스트 MSE: {:.5f}".format(name, test_loss))
    print()

    return optimizer, hist
    
def main():
    tf.random.set_seed(2022)
    np.random.seed(2022)

    window_size = 50
    X_train, X_test, y_train, y_test = load_data(10000, window_size)

    rnn_model = build_rnn_model(window_size)
    run_model(rnn_model, X_train, X_test, y_train, y_test, name="RNN")

    deep_rnn_model = build_deep_rnn_model(window_size)
    run_model(deep_rnn_model, X_train, X_test, y_train, y_test, name="Deep RNN")


if __name__ == "__main__":
    main()


Epoch 1/20
32/32 - 2s - loss: 0.1129 - 2s/epoch - 53ms/step
Epoch 2/20
32/32 - 0s - loss: 0.0186 - 364ms/epoch - 11ms/step
Epoch 3/20
32/32 - 0s - loss: 0.0065 - 360ms/epoch - 11ms/step
Epoch 4/20
32/32 - 0s - loss: 0.0032 - 332ms/epoch - 10ms/step
Epoch 5/20
32/32 - 0s - loss: 0.0027 - 339ms/epoch - 11ms/step
Epoch 6/20
32/32 - 0s - loss: 0.0026 - 357ms/epoch - 11ms/step
Epoch 7/20
32/32 - 0s - loss: 0.0025 - 340ms/epoch - 11ms/step
Epoch 8/20
32/32 - 0s - loss: 0.0024 - 333ms/epoch - 10ms/step
Epoch 9/20
32/32 - 0s - loss: 0.0023 - 342ms/epoch - 11ms/step
Epoch 10/20
32/32 - 0s - loss: 0.0023 - 339ms/epoch - 11ms/step
Epoch 11/20
32/32 - 0s - loss: 0.0022 - 348ms/epoch - 11ms/step
Epoch 12/20
32/32 - 0s - loss: 0.0022 - 343ms/epoch - 11ms/step
Epoch 13/20
32/32 - 0s - loss: 0.0021 - 334ms/epoch - 10ms/step
Epoch 14/20
32/32 - 0s - loss: 0.0021 - 339ms/epoch - 11ms/step
Epoch 15/20
32/32 - 0s - loss: 0.0020 - 357ms/epoch - 11ms/step
Epoch 16/20
32/32 - 0s - loss: 0.0020 - 337ms/epoch 

# Encoder-Decoder 구현
: Encoder의 hidden state를 가져와서 Decoder의 초기 hidden state로 사용함

In [14]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras import layers, Sequential, Input

class EncoderDecoder(Model):
    def __init__(self, hidden_dim, encoder_input_shape, decoder_input_shape, num_classes):
        super(EncoderDecoder, self).__init__()
        
        # SimpleRNN으로 이루어진 Encoder
        self.encoder = layers.SimpleRNN(hidden_dim, return_state=True,input_shape=encoder_input_shape)
        # return_state: hidden_state를 쓰기 위함    

        # SimpleRNN으로 이루어진 Decoder.
        self.decoder = layers.SimpleRNN(hidden_dim, return_sequences=True, input_shape=decoder_input_shape)
        
        self.dense = layers.Dense(num_classes, activation="softmax")
        
    def call(self, encoder_inputs, decoder_inputs):
        # Encoder에 입력값을 넣어 Decoder의 초기 state로 사용할 state를 얻어냄
        _, encoder_state = self.encoder(encoder_inputs) # _로 표현하여 값이 있지만 사용하지 않음을 명시적으로 나타냄
        # - encoder_output은 필요없다. encoder의 hidden state만 필요!
        
        # Decoder에 입력값을 넣고, 초기 state는 Encoder에서 얻어낸 state로 설정
        decoder_outputs = self.decoder(decoder_inputs, initial_state=[encoder_state])
        
        outputs = self.dense(decoder_outputs)
        
        return outputs


def main():
    # hidden state의 크기
    hidden_dim = 20
    
    # Encoder에 들어갈 각 데이터의 모양
    encoder_input_shape = (10, 1)
    
    # Decoder에 들어갈 각 데이터의 모양
    decoder_input_shape = (30, 1)
    
    # 분류한 클래스 개수
    num_classes = 5

    # Encoder-Decoder 모델
    model = EncoderDecoder(hidden_dim, encoder_input_shape, decoder_input_shape, num_classes)
    
    # 모델에 넣어줄 가상의 데이터를 생성
    encoder_x, decoder_x = tf.random.uniform(shape=encoder_input_shape), tf.random.uniform(shape=decoder_input_shape)
    encoder_x, decoder_x = tf.expand_dims(encoder_x, axis=0), tf.expand_dims(decoder_x, axis=0)
    y = model(encoder_x, decoder_x)

    # 모델의 정보를 출력
    model.summary()

if __name__ == "__main__":
    main()

Model: "encoder_decoder"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_6 (SimpleRNN)    multiple                  440       
                                                                 
 simple_rnn_7 (SimpleRNN)    multiple                  440       
                                                                 
 dense_4 (Dense)             multiple                  105       
                                                                 
Total params: 985
Trainable params: 985
Non-trainable params: 0
_________________________________________________________________
